apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-collector-config
  namespace: honeycomb
data:
  config.yml: |
    exporters:
      otlp:
        endpoint: "api.eu1.honeycomb.io:443"
        headers:
          x-honeycomb-team: "${env:HONEYCOMB_API_KEY}"
      debug:
        verbosity: normal
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-collector
  namespace: honeycomb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-collector
  template:
    metadata:
      labels:
        app: telemetry-collector
    spec:
      containers:
      - name: telemetry-collector
        image: otel/opentelemetry-collector:0.110.0
        args:
        - --config=/opentelemetry/config.yml
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb
              key: HONEYCOMB_API_KEY
        ports:
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: telemetry-collector-config
          mountPath: /opentelemetry
      volumes:
      - configMap:
          name: telemetry-collector-config
        name: telemetry-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-collector
  namespace: honeycomb
  labels:
    app: telemetry-collector
spec:
  ports:
    - name: grpc
      port: 4317
    - name: http
      port: 4318
  selector:
    app: telemetry-collector